server:
  address: 0.0.0.0
  port: 8081

listingproject:
  host: http://localhost:8081


logging:
  level:
    root: DEBUG

spring:
  datasource:
    url: "jdbc:h2:file:./data/testdb"
    username: "test"
    password: "test"
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: never